### ISSUE TITLE
Grammar and clarity improvements

### ISSUE THREAD

**Issue by szaydel** [pedropark99/zig-book#102]
Thank you for working on this book. I am sure the value is going to be immense to many people. I am wondering if you have interest in edits that improve clarity and grammar? Here’s an example of what I have done so far: https://github.com/pedropark99/zig-book/compare/main...szaydel:zig-book:topic/szaydel/ch1-language?diff=split&w=

If so, I am happy to work on improvements in this and other chapters. Thanks!

**Comment by pedropark99** [comment]
Hey @szaydel ! I was off these last days. But answering this question:

> I am wondering if you have interest in edits that improve clarity and grammar?

The answer is yes! I am more than happy to review PR's that brings new improvements and fix my grammar mistakes 😉. Part of the reason why this book is open source is to be open for contributions from the community 🥳🎉.

**Comment by pedropark99** [comment]
@szaydel  If you need some inspiration on "how to do this", you can take a look at this PR from @icholy 

https://github.com/pedropark99/zig-book/pull/91

It is also a good idea to read the [CONTRIBUTING.md](https://github.com/pedropark99/zig-book/blob/main/CONTRIBUTING.md) file in the repo, which give you some instructions.

**Comment by szaydel** [comment]
Thank you for the pointer. And I had a look at `CONTRIBUTING.md`, but will be sure to review.
