### ISSUE TITLE
Idea for chapter about structs and modules

### ISSUE THREAD

**Issue by pedropark99** [pedropark99/zig-book#11]
Maybe... just maybe, it is worth it to create a whole chapter just to talk about structs. Currently, structs in Zig are presented at section 1.10:

https://pedropark99.github.io/zig-book/Chapters/01-zig-weird.html#sec-structs-and-oop

But it might be worth it to give it a more detailed description, and mix both "structs" and "modules". Because modules in Zig are structs, so, you can write a module as if it was a struct, this particular module is an example of that:

https://github.com/kprotty/zap/blob/blog/src/thread_pool.zig

Anyway, might be a good idea to create a separate chapter for that.

**Comment by kassane** [comment]
Firstly, your idea for the book is cool.

It is worth mentioning that Zig, D, Rust does not have a public/private owner in the concept of inheritance. However there is only pub or "non-pub" content module.

The concept of an interface using `@fieldParentPtr`.

![](https://github.com/SuperAuguste/zig-patterns/raw/main/.github/assets/field_parent_ptr.svg) by SuperAuguste

### References
- https://www.openmymind.net/Zig-Interfaces/
- https://github.com/TheAlgorithms/Zig/blob/main/dataStructures/lruCache.zig
- https://github.com/SuperAuguste/zig-patterns/blob/main/src/typing/field_parent_ptr.zig

**Comment by pedropark99** [comment]
Hello @kassane ! First of all, thank you for your comment! Now, I am not sure if it is worth talking about interfaces in this book. Because interfaces are a pattern commonly found in object oriented language (such as C++), and Zig is not one of them. As a consequence, Zig does not offer clear tools to make an interface.

It is possible to make an interface in Zig, but since we don't have clear tools to make them, this becomes more of an "advanced or very specific type of knowledge" in Zig.
