### ISSUE TITLE
Project1: a better way to perform ceiled division

### ISSUE THREAD

**Issue by Pokryton** [pedropark99/zig-book#33]
In Project 1 of this book, when calculating the size of an encoded or decoded string, ceiled division of `usize` is done by casting to `f64` and calling the `@ceil` function.

https://github.com/pedropark99/zig-book/blob/5879b294a172a9897d4877335271440ca302493c/Chapters/01-base64.qmd#L260-L279

While this approach works, it may lost precision in extreme cases (unlikely though), and floating point arithmetic is generally much more expensive than integer arithmetic.  A better approach would be to use `std.math.divCeil(usize, input.len, 3)` or simply `(input.len + 2) / 3`. This is also easier to read IMO.

For reference, here's how the same functionality implemented in the standard library.

https://github.com/ziglang/zig/blob/218cf059dd215282aa96d6b4715e68d533a4238e/lib/std/base64.zig#L93-L100

**Comment by pedropark99** [comment]
Hey @Pokryton ! First of all, thank you for your comment!
It is a good suggestion. I will make it happen 😉
