### ISSUE TITLE
References to Rust

### ISSUE THREAD

**Issue by sroller** [pedropark99/zig-book#36]
i’m very happy i found this project!!
I started to read the introduction of your book.
I noticed there are several statements like ‘Zig is not like Rust’.
I find this irritating. I have no clue what Rust does. Is it necessary to know Rust in order to understand this text? I guess not, correct?
You might want to consider this. I believe occasional references to C might be ok, because C is the mostly known grandfather of this language family. Rust, IMHO, is not.

keep going with the book though! It’s very exciting.

**Comment by pedropark99** [comment]
First of all, thank you for your comment @sroller ! Now, talking specifically about your main question:

>  Is it necessary to know Rust in order to understand this text?

The second paragraph in the first chapter of this book already answered your question:

> I assume you have previous experience with some programming language in this book, not necessarily with a low-level one. So, if you have experience with Python, or Javascript, for example, is fine. But, if you do have experience with low-level languages, such as C, C++, or Rust, you will probably learn faster throughout this book.

Peace 😉✌️!
