### ISSUE TITLE
Section about immutable function arguments

### ISSUE THREAD

**Issue by kurz-m** [pedropark99/zig-book#68]
This might be a little bit picky, but in the section `2.2. Function parameters are immutable`, you are talking about handing function arguments by value or by reference to a function. In the end, everything is handed by value, because even if you are handing a pointer, the pointer (more like where it points) is immutable. Only the value, where it points to can be changed by dereferencing the value and then changing it, like you perfectly showed in the seccond `add2(x: *u32) void` function. This is quite similar to how it works in `C`.

Maybe the following section could be slightly rephrased to point out this difference:

https://github.com/pedropark99/zig-book/blob/3a02942229000e0bea213f4fdd6d79ba4f57b3c6/Chapters/03-structs.qmd#L657-L664

Thanks for your effort on the book and I am looking forward to hearing your take on this ;)

**Comment by pedropark99** [comment]
Oh! I see what you mean! My thoughts in this are:

- I like the idea to make this difference clear, that the pointer itself is still immutable, but the pointer can be used to change the value that it points to.
- Although the pointer itself is a value (i.e. an integer that represents a memory address), and it is passed to the function by value, I think is still best to stick with "passed by reference" when talking about passing pointers to functions.

Does this sound reasonable?

**Comment by kurz-m** [comment]
Sounds totally reasonable!
I agree with what you said.

+ During my walkthrough of the book I also try to keep the language as close as possible to how you wrote it because I do not want to change your style of writing. Just some typos and grammatical changes I want to add. I hope that's fine.
