### ISSUE TITLE
Clarification of Chapter 3 Memory and Allocation

### ISSUE THREAD

**Issue by kurz-m** [pedropark99/zig-book#69]
I am not fully understanding this paragraph:

https://github.com/pedropark99/zig-book/blob/3a02942229000e0bea213f4fdd6d79ba4f57b3c6/Chapters/01-memory.qmd#L26-L28

Do you mean every program needs memory? You switch between computers and programs e.g. in the last sentence you are talking about programming languages. Maybe rephrasing it something like this would make it clearer:

> [!NOTE]
Computers fundamentally rely on memory to function. This memory acts as a temporary storage space for the data and results generated during computations.  Without memory, the core concepts of programming languages, such as "variables" and "objects" which hold these values, would be impossible. In essence, memory provides the foundation for data manipulation and storage within a computer system, enabling the execution of programs written in any language.

**Comment by pedropark99** [comment]
I see your point. Good suggestion of rephrasing it.
