### ISSUE TITLE
3.2.6 Buffer allocators

### ISSUE THREAD

**Issue by chrboesch** [pedropark99/zig-book#82]
"The FixedBufferAllocator() and ThreadSafeFixedBufferAllocator() are allocator objects that work with a fixed sized buffer **that is stored in the stack**."
This is not entirely true. It depends on the size and the way you allocate the buffer. In your example with the fixed size at compile time, it is true. But if you allocate the buffer like this, for example:
```zig
    const heap = std.heap.page_allocator;
    const memory_buffer = try heap.alloc(u8, 100 * 1024 * 1024); // 100 MB memory
    defer heap.free(memory_buffer);
    var fba = std.heap.FixedBufferAllocator.init(memory_buffer);
    const allocator = fba.allocator();
```
then the buffer wouldn't fit into the stack. But it's still fast because you only have a memory allocation at the beginning.

My suggestion would be to explain the buffer memory in a little more detail, because it's worth it. And add my example of a large buffer, which is also very fast because you don't need any further memory allocation from the operating system.

**Comment by pedropark99** [comment]
Thank you @chrboesch !

**Comment by pedropark99** [comment]
Related to #46
